### ISSUE TITLE
Fails to install because of yoeunes/notify

### ISSUE THREAD

**Issue by goldug** [Havenstd06/Limg#139]
The step "composer install" fails because yoeunes/notify does no longer exist. The repo is gone.
The author recommends php-flasher/flasher-laravel instead.

**Comment by yoeunes** [comment]
Hello @goldug sorry for the issue, I have just re-pushed [yoeunes/notify](https://github.com/yoeunes/notify), and I created this [PR](https://github.com/Havenstd06/Limg/pull/140) to replace it with [PHPFlasher](https://php-flasher.io)

**Comment by Havenstd06** [comment]
> Hello @goldug sorry for the issue, I have just re-pushed [yoeunes/notify](https://github.com/yoeunes/notify), and I created this [PR](https://github.com/Havenstd06/Limg/pull/140) to replace it with [PHPFlasher](https://php-flasher.io)

Thanks you very much for your PR 😀

**Comment by yoeunes** [comment]
You're welcome, and congratulations on this project, I really liked it 👍
