### ISSUE TITLE
I can't able to upload any video 

### ISSUE THREAD

**Issue by ravicant** [Havenstd06/Limg#90]
it not accepting any video from sharex

**Comment by fieu** [comment]
Can you give us more information? Saying something doesn't work doesn't help us. Give us an error, something.

**Comment by ravicant** [comment]
https://k.ravicant.in/i/FR1lsb.png
here u go the main issue I am getting when I upload through sharex size and everything is good

**Comment by ravicant** [comment]
i just checked logs too i got this msg - [Sat Jan 30 19:09:28 2021] PHP Warning:  POST Content-Length of 19768422 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
[Sat Jan 30 19:09:29 2021] 127.0.0.1:35058 Closing
[Sat Jan 30 19:09:29 2021] 127.0.0.1:35060 Accepted
[Sat Jan 30 19:09:29 2021] 127.0.0.1:35060 Closing
[Sat Jan 30 19:09:42 2021] 127.0.0.1:35064 Accepted
[Sat Jan 30 19:09:42 2021] PHP Warning:  POST Content-Length of 19768422 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
[Sat Jan 30 19:09:42 2021] 127.0.0.1:35064 Closing
[Sat Jan 30 19:09:44 2021] 127.0.0.1:35066 Accepted
[Sat Jan 30 19:09:44 2021] 127.0.0.1:35066 Closing
[Sat Jan 30 19:09:57 2021] 127.0.0.1:35070 Accepted
[Sat Jan 30 19:09:57 2021] 127.0.0.1:35070 Closing
[Sat Jan 30 19:10:14 2021] 127.0.0.1:35074 Accepted
[Sat Jan 30 19:10:14 2021] 127.0.0.1:35074 Closing
[Sat Jan 30 19:10:16 2021] 127.0.0.1:35078 Accepted
[Sat Jan 30 19:10:16 2021] 127.0.0.1:35078 Closing
[Sat Jan 30 19:10:37 2021] 127.0.0.1:35082 Accepted
[Sat Jan 30 19:10:37 2021] 127.0.0.1:35082 Closing
[Sat Jan 30 19:11:00 2021] 127.0.0.1:35086 Accepted
[Sat Jan 30 19:11:00 2021] PHP Warning:  POST Content-Length of 19768422 bytes exceeds the limit of 8388608 bytes in Unknown on line 0
[Sat Jan 30 19:11:00 2021] 127.0.0.1:35086 Closing
[Sat Jan 30 19:11:13 2021] 127.0.0.1:35088 Accepted
[Sat Jan 30 19:11:13 2021] PHP Warning:  POST Content-Length of 19768422 bytes exceeds the limit of 8388608 bytes in Unknown on line 0

**Comment by fieu** [comment]
> [Sat Jan 30 19:09:28 2021] PHP Warning: POST Content-Length of 19768422 bytes exceeds the limit of 8388608 bytes in Unknown on line 0

This means the video you are trying to upload is too large. Try with a smaller file.

**Comment by fieu** [comment]
Please close this ticket if you have no further questions.

**Comment by ravicant** [comment]
can i change or no i was checking where i can change?

**Comment by Havenstd06** [comment]
> can i change or no i was checking where i can change?

This file contains all the information about the upload from the api

https://github.com/Havenstd06/Limg/blob/master/app/Http/Controllers/API/ImageController.php#L72

**Comment by ravicant** [comment]
thanks i will check
